name: Docker test 2
on: 
#  release:
#    types: [published]
  push

jobs:
  build:
#    name: Docker test 2
    strategy:
        matrix:
#            r-os: [r3.6.3-centos7, r4.1.0-centos7]
            r-os: [r3.6.3-centos7]
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: |
            yuri05/base-r3.6.3-centos7:latest
            yuri05/base-r3.6.3-centos7:${{ steps.tag_name.outputs.SOURCE_TAG}}
            ghcr.io/yuri05/base-r3.6.3-centos7:latest
            ghcr.io/yuri05/base-r3.6.3-centos7:${{ steps.tag_name.outputs.SOURCE_TAG}}
#            docker.pkg.github.com/yuri05/hello-github-actions/base-r3.6.3-centos7:${{ steps.tag_name.outputs.SOURCE_TAG}}
