ARG rversion
FROM rstudio/r-base:${rversion}-centos7

ENTRYPOINT ["sh"]

# Copy installation scripts
RUN mkdir -p /tmp_setup 
COPY .github/workflows/*.R /tmp_setup/
COPY .github/workflows/*.sh /tmp_setup/
RUN chmod ugo+x /tmp_setup/*.sh

# Install mono, dotnet-sdk and required packages
RUN /tmp_setup/install_mono_net_packages_centos7.sh

# Install R package dependencies
RUN R --no-save -e "source('/tmp_setup/install_packages.R')"

# Setup environment 
ENV LC_ALL=en_US.UTF-8
ENV LD_LIBRARY_PATH="/usr/lib64/openmpi/lib:/opt/R/${rversion}/lib/R/library/ospsuite/lib:$LD_LIBRARY_PATH"
ENV PATH="/opt/R/${rversion}/bin:${PATH}"

#Install pandoc and Rmpi
RUN /tmp_setup/install_pandoc_rmpi.sh

# Cleanup
RUN rm -rf /tmp_setup